### ISSUE TITLE
One question about Matrix

### ISSUE THREAD

**Issue by zym10031** [MDS-book/MDS-book#2]
On Page 38, within grey box on the top: it is said that "...The aij are typically real numbers but can also be integer numbers..." As I know, the integer numbers are sub-class of real numbers. What does this sentence exactly mean? Tks

**Comment by ssandfeld** [comment]
Thanks for asking -- from a purely mathematical point of view you are right. The explicit mentioning of integer numbers was to remind those who rather have the "numpy perspective" where there are arrays with different number types. But I'll keep your comment in mind!

**Comment by zym10031** [comment]
Oh, I See. Thank you very much!
