### ISSUE TITLE
notation issue

### ISSUE THREAD

**Issue by IAM-DW** [MDS-book/MDS-book#4]
Hi Stefan,
some minor issues:
page 451:  Example 16.3 last line: "Therefore, it has slightly...:"  remaining part of the sentence seems missing
page 504:  $\partial J/\partial b_3$ ? from the bias of the last layer is missing in the text
page 503: $b_3$ to be added to eq. 18.7, 18.14 ; in eq. 18.9 the bias  $b_3$ is  included.
 *  equation 18.39: it should be  $W^{(k)T}$ transposed  and also in its later occurrence  (eq. 18.47) 
    $\partial J/\partial y_i^{(k-1)}=\partial J/\partial y_r^{(k)} w_{ir}^{(k)} $ 
     in index notation
  
 *  equation 18.51: the derivative of the activation function got lost...
  
nice work.
Best,
DW

**Comment by ssandfeld** [comment]
Thanks, I've added them to the list of errata on the book's webpage.
